//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageGallery.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebFile
    {
        public int Id { get; set; }
        public byte[] Data { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public int FileLength { get; set; }
        public string ContentType { get; set; }
    }
}
